#USD
- id:                    krw
  symbol:                '￦'
  type:                  fiat
  precision:             2
  base_factor:           1
  enabled:               true
  min_deposit_amount:    0
  min_collection_amount: 0
  withdraw_limit_24h:    10000000
  withdraw_limit_72h:    20000000
  deposit_fee:           0
  withdraw_fee:          0

- id:                    eth
  blockchain_key:        eth-rinkeby
  symbol:                'Ξ'
  type:                  coin
  precision:             8
  base_factor:           1_000_000_000_000_000_000
  enabled:               true
  min_deposit_amount:    0.00021
  min_collection_amount: 0.00021
  withdraw_limit_24h:    0.2
  withdraw_limit_72h:    0.5
  deposit_fee:           0
  withdraw_fee:          0
  options:
    case_sensitive:                   false
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             false
    allow_multiple_deposit_addresses: false
    api_client: ETH
    json_rpc_endpoint:        http://geth:8545
    wallet_url_template:      https://rinkeby.etherscan.io/address/#{address}
    transaction_url_template: https://rinkeby.etherscan.io/tx/#{txid}
